In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\Summer Internship\titanic.csv")

In [4]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [5]:
print("\nDataset Shape:")
print(df.shape)

Dataset Shape:
(418, 12)

In [6]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
print("\nData Types:")
print(df.dtypes)

Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
columns = ['Age', 'Income', 'CCAvg']

for col in columns:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [12]:
columns = ['Embarked']

for col in columns:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mode()[0])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [14]:
if 'Cabin' in df.columns:
    df.drop(columns=['Cabin'], inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,C

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
categorical_columns = ['Survived', 'Pclass', 'Sex']

for col in categorical_columns:
    if col in df.columns:
        df[col] = df[col].astype('category')

In [19]:
print(df.dtypes)

PassengerId       int64
Survived       category
Pclass         category
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked         object
dtype: object

In [21]:
df.rename(columns={
    'PassengerId': 'Passenger_ID',
    'Pclass': 'Passenger_Class',
    'Name': 'Passenger_Name',
    'Sex': 'Gender'
}, inplace=True)
df

,Passenger_ID,Survived,Passenger_Class,Passenger_Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,C

In [23]:
print("\nCleaned Dataset Info:")
print(df.info())

Cleaned Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Passenger_ID     418 non-null    int64
 1   Survived         418 non-null    category
 2   Passenger_Class  418 non-null    category
 3   Passenger_Name   418 non-null    object
 4   Gender           418 non-null    category
 5   Age              418 non-null    float64
 6   SibSp            418 non-null    int64
 7   Parch            418 non-null    int64
 8   Ticket           418 non-null    object
 9   Fare             418 non-null    float64
 10  Embarked         418 non-null    object
dtypes: category(3), float64(2), int64(3), object(3)
memory usage: 27.8+ KB
None

In [24]:
print("\nFirst 10 Rows After Cleaning:")
print(df.head(10))

First 10 Rows After Cleaning:
   Passenger_ID Survived Passenger_Class  \
0           892        0               3
1           893        1               3
2           894        0               2
3           895        0               3
4           896        1               3
5           897        0               3
6           898        1               3
7           899        0               2
8           900        1               3
9           901        0               3

                                 Passenger_Name  Gender   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                     Myles, Mr. Thomas Francis    male  62.0      0      0
3                              Wirz, Mr. Albert    male  27.0      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
5                    Svensson, Mr. Johan Cervin    male  14.0      0      0
6                          Connolly, Miss. Kate  female  30.0      0      0
7                  Caldwell, Mr. Albert Francis    male  26.0      1      1
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0      0
9                       Davies, Mr. John Samuel    male  21.0      2      0

      Ticket     Fare Embarked
0     330911   7.8292        Q
1     363272   7.0000        S
2     240276   9.6875        Q
3     315154   8.6625        S
4    3101298  12.2875        S
5       7538   9.2250        S
6     330972   7.6292        Q
7     248738  29.0000        S
8       2657   7.2292        C
9  A/4 48871  24.1500        S

In [26]:
df.to_csv('cleaned_titanic_dataset.csv', index=False)

print("\nCleaned dataset is saved")

Cleaned dataset is saved